# Generated by Django 5.2.1 on 2025-05-21 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0005_remove_contact_subject_alter_contact_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='province',
            field=models.CharField(blank=True, choices=[('Kigali', 'Kigali'), ('Eastern', 'Eastern'), ('Western', 'Western'), ('Northern', 'Northern'), ('Southern', 'Southern')], max_length=20, null=True),
        ),
    ]
